name: Reject PR Workflow

on:
  workflow_run:
    workflows: ["Python Code Quality"]
    types:
      - completed

jobs:
  reject_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check job status
        id: check_status
        run: |
          if [ "$failure" == "true" ]; then
            echo "::set-output name=status::failure"
          else
            echo "::set-output name=status::success"
          fi
      
      - name: Reject Pull Request
        if: steps.check_status.outputs.status == 'failure'
        run: |
          PR_NUMBER=${{ github.event.workflow_run.head_workflow_run.event.pull_request.number }}
          API_URL="https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER"

          # Comment on the pull request
          curl -s -X POST "$API_URL/reviews" -H "Authorization: token ${{ secrets.GH_TOKEN }}" -H "Accept: application/vnd.github.v3+json" \
            -d "{\"body\":\"Sorry, your pull request did not pass code quality checks. It has been rejected.\"}"

          # Optionally, close the pull request (uncomment the next line to close)
          #curl -s -X PATCH "$API_URL" -H "Authorization: token ${{ secrets.GH_TOKEN }}" -H "Accept: application/vnd.github.v3+json" \
          #  -d "{\"state\":\"closed\"}"
