name: Python Code Quality

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main 

jobs:
  check_code_quality:
    name: Check code quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint --fail-under=${{ vars.branch_code_quality_threshold }}

      - name: Check Unused Imports
        run: |
          pylint --fail-under=${{ vars.branch_code_quality_threshold }} --disable=all --enable=unused-import ./**/*.py

      - name: Check Import Order
        run: |
          pylint --fail-under=${{ vars.branch_code_quality_threshold }} --load-plugins pylint --fail-under=${{ vars.branch_code_quality_threshold }}_ordering --disable=all --enable=wrong-import-order ./**/*.py
      - name: Check PEP 8 Compliance
        run: pylint --fail-under=${{ vars.branch_code_quality_threshold }} --disable=all --enable=pep8 ./**/*.py

      - name: Check Docstring Conventions
        run: pylint --fail-under=${{ vars.branch_code_quality_threshold }} --disable=all --enable=missing-docstring ./**/*.py

      - name: Check Naming Conventions
        run: pylint --fail-under=${{ vars.branch_code_quality_threshold }} --disable=all --enable=naming ./**/*.py

      - name: Check Cyclomatic Complexity
        run: pylint --fail-under=${{ vars.branch_code_quality_threshold }} --disable=all --enable=bad-continuation ./**/*.py

      - name: Check Resource Management
        run: pylint --fail-under=${{ vars.branch_code_quality_threshold }} --disable=all --enable=resource-leakage ./**/*.py

      - name: Check for Duplicated Code
        run: pylint --fail-under=${{ vars.branch_code_quality_threshold }} --disable=all --enable=duplicate-code ./**/*.py

      - name: Check for Security Vulnerabilities
        run: bandit -r ./

      # - name: Check Dependency Security
      #   run: safety check --full-report

      - name: Lint Code
        run: |
          pylint --fail-under=${{ vars.branch_code_quality_threshold }} --load-plugins pylint --fail-under=${{ vars.branch_code_quality_threshold }}_ordering ./**/*.py

  deploy:
    name: Deploy Code
    runs-on: ubuntu-latest
    needs: check_code_quality
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to Production
        run: |
          echo "Aqui eu faço o deploy..."
