name: Python Code Quality

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main 

jobs:
  check_unused_imports:
    name: Check Unused Imports
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Check Unused Imports
        run: |
          pylint --disable=all --enable=unused-import ./**/*.py

  check_import_order:
    name: Check Import Order
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Check Import Order
        run: |
          pylint --load-plugins pylint_ordering --disable=all --enable=wrong-import-order ./**/*.py

  lint_code:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Lint Code
        run: |
          pylint --load-plugins pylint_ordering ./**/*.py
